FROM python:3.9.1-buster

WORKDIR /opt/app/
ADD Pipfile Pipfile.lock polyglot_download.py ./
RUN pip install pipenv
RUN pipenv install --system --deploy --ignore-pipfile
RUN mkdir /root/polyglot_data
RUN python polyglot_download.py
RUN python -m spacy download xx_ent_wiki_sm
RUN python -m spacy download en_core_web_sm
