#!/bin/bash -ex

cd "$(dirname ${BASH_SOURCE[0]})"

if [ -n "$NLP_SERVICE_PRESET" ]; then
  echo "Loading preset $NLP_SERVICE_PRESET"
  export NLP_SERVICE_MODELS_JSON="$(cat ./presets/$NLP_SERVICE_PRESET.json)"
fi

# must use sync for timeout to work:
# https://github.com/benoitc/gunicorn/issues/2695
exec gunicorn -b 0.0.0.0:5000 \
  --name nlp-service \
  --timeout=600 \
  --worker-class=sync --workers 8 --threads 1 \
  --max-requests 40 --max-requests-jitter 30 \
  entity_extractor:app
