#!/bin/bash -ex

cd "$(dirname ${BASH_SOURCE[0]})"

if [ -n "$NLP_SERVICE_PRESET" ]; then
  echo "Loading preset $NLP_SERVICE_PRESET"
  export NLP_SERVICE_MODELS_JSON="$(cat ./presets/$NLP_SERVICE_PRESET.json)"
fi

#run the server
echo "starting server"
exec gunicorn -b 0.0.0.0:5000 \
  --timeout=3600 \
  --worker-class=gthread --threads 8 --workers 5 \
  --max-requests 100 --max-requests-jitter 50 \
  app:app
